### PR TITLE
IAMP-1484 : add set error code

### PR DESCRIPTION
**Pull request by banukusuma**
add set error code if a request has an error when return redirect response (302)

### CODE REVIEW

**Comment by anggorodewanto** [comment]
What is this for?

**Comment by banukusuma** [comment]
This PR for adding error code in query response, 
The endpoint is /auth, so when user is disabled, its only return error=access_denied&error_description=user is disabled on it response

I want to add the error_code=(some error code) , so the login website can check whether the user is deactivate by admin or the user itself

**Comment by anggorodewanto** [comment]
Can we do it without modifying Osin?

**Comment by banukusuma** [comment]
apparently, we can do it without modifying the osin, by adding the error_code query param into osin.Response URL, 
i will close the PR then

**Pull request closed without merging**
